apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: react-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-demo
spec:
  source:
    git:
      url: https://github.com/Mpluya/react-hello-world
      ref:
        branch: main