apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: react-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-demo
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/language: nodejs
    supplychain: unicorn
spec:
  source:
    git:
      url: https://github.com/Mpluya/react-hello-world
      ref:
        branch: main
